version: '3.9'

services:
  traefik:
    build:
      context: ./traefik
    container_name: traefik
    security_opt:
      - no-new-privileges:true
    command:
        - --certificatesresolvers.letsencrypt.acme.email=${EMAIL}
        # - --pilot.token=${PILOT_TOKEN}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_data:/etc/traefik/acme:z
      - ./traefik/log:/var/log/traefik
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/dynamic:/etc/traefik/dynamic
      - /etc/localtime:/etc/localtime:ro
    env_file: .env

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=front"
      # - "traefik.port=8080"
      # - "traefik.backend=traefik"

      # Secure Dashboard (http basic auth)
      - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_DASHBOARD}.${DOMAIN}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      # - "traefik.http.routers.dashboard.middlewares=security-headers@file,dashboard-auth"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth"
      # Dashboard auth
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=${DASHBOARD_LOG_PSW}"

    restart: unless-stopped
    networks:
      - front

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prometheus/rules.yml:/etc/prometheus/rules.yml
      - prometheus_data:/prometheus
      # - /etc/localtime:/etc/localtime:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - front
      - back

  nodeexporter:
    image: prom/node-exporter
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.processes
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    networks:
      - back

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /etc/localtime:/etc/localtime:ro
      - /sys:/sys:ro
      - /var/disk:/var/disk:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run:/var/run:ro
    networks:
      - back

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - /etc/localtime:/etc/localtime:ro
      - grafana_data:/var/lib/grafana
    env_file:
      - .env
    networks:
      - front
      - back

volumes:
  traefik_data: {}
  prometheus_data: {}
  grafana_data: {}

networks:
  front:
    name: front
  back:
    name: back
