# At startup, Traefik searches for a file named traefik.yml (or traefik.yaml or traefik.toml) in /etc/traefik/

global:
  sendAnonymousUsage: false
  checkNewVersion: false

api:
  # insecure: true
  dashboard: true
  # debug: true

entryPoints:
  web:
    address: ":80"
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https
  websecure:
    address: ":443"

  metrics:
    address: ":9090"

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addServicesLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    watch: true  # Watch Docker Swarm events
    # swarmMode: true  # false by default
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      storage: "/etc/traefik/acme/acme.json"
      # caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"  # Staging server
      # caServer: "https://acme-v02.api.letsencrypt.org/directory"  # Used by default
      tlsChallenge: true
      keyType: EC256  # Allow value 'EC256', 'EC384', 'RSA2048', 'RSA4096', 'RSA8192'
      # httpChallenge:
      #   entryPoint: web

log:
  filePath: "/var/log/traefik/applog.log"
  # format: json
  level: INFO

accessLog:
  filePath: "/var/log/traefik/access.log"
  # format: json
  # filters:
  #   statusCodes:
  #     - "200"
  #     - "300-302"
  #   retryAttempts: true
  #   minDuration: "10ms"
  fields:
    defaultMode: keep
    # names:
    #   ClientUsername: drop
    headers:
      defaultMode: keep
      names:
          User-Agent: keep
          Authorization: drop
          Content-Type: keep

# pilot:
#   token: ""
#   dashboard: true
