# http:
#   routers:
    # dashboard:
    #   service: api@internal
    #   tls:
    #     certresolver: letsencrypt
    #   entrypoints:
    #     - websecure
    #   middlewares:
    #     - security-headers

    # rt-prometheus:
    #   entryPoints:
    #   - websecure
    #   # middlewares:
    #   # - authentification
    #   service: sc-prometheus
    #   rule: Host (`prom.scansite.ru`)
    #   tls:
    #     certResolver: letsencrypt

    # rt-grafana:
    #   entryPoints:
    #   - websecure
    #   # middlewares:
    #   # - security
    #   service: sc-grafana
    #   rule: Host (`gr.scansite.ru`)
    #   tls:
    #     certResolver: letsencrypt
